=== SimonPatrickReyes/Lenguajes/biblioteca.dtd
<!DOCTYPE biblioteca [
<!-- Definición de elementos -->
<!ELEMENT biblioteca (libro,revista,periodico+)>
<!ELEMENT libro (claseL,tituloL,capituloL,indiceL,sinopsisL)>
<!ELEMENT claseL (#PCDATA)>
<!ELEMENT tituloL (#PCDATA)>
<!ELEMENT capituloL (ctitulo,ccontenido)>
<!ELEMENT ctitulo (#PCDATA)>
<!ELEMENT ccontenido (#PCDATA)>
<!ELEMENT indiceL (#PCDATA)>
<!ELEMENT sinopsisL (#PCDATA)**>
<!ELEMENT revista (claseR,tituloR,nrev,indiceR,seccionR)>
<!ELEMENT claseR (#PCDATA)>
<!ELEMENT tituloR (#PCDATA)>
<!ELEMENT nrev (#PCDATA)>
<!ELEMENT indiceR (#PCDATA)>
<!ELEMENT seccionR (contenidoR)>
<!ELEMENT contenidoR (#PCDATA)>
<!ELEMENT periodico (claseP,seccionP,indiceP,contenidoP)>
<!ELEMENT claseP (#PCDATA)>
<!ELEMENT seccionP (articuloP)>
<!ELEMENT articuloP (#PCDATA)>
<!ELEMENT indiceP (#PCDATA)>
<!ELEMENT contenidoP (#PCDATA)>
<!-- Definición de atributos -->    
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro npag CDATA #REQUIRED>
<!ATTLIST claseL tipo_claseL (novela | infantil | didactico) #REQUIRED>
<!ATTLIST capituloL npag CDATA #REQUIRED>
<!ATTLIST ccontenido informacionL CDATA #REQUIRED>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista npag CDATA #REQUIRED>
<!ATTLIST claseR tipo_claseR (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST seccionR npag CDATA #REQUIRED>
<!ATTLIST contenidoR informacionR CDATA #REQUIRED>
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST claseP tipo_claseP (nacional | internacional) #REQUIRED>
<!ATTLIST claseP fpub CDATA #REQUIRED>
<!ATTLIST seccionP tipsec (economica | opinion | deportes | nacional | internacional) #REQUIRED>
<!ATTLIST articuloP autor CDATA #REQUIRED>
<!ATTLIST contenidoP informacionP CDATA #REQUIRED>
    
]>

=== SimonPatrickReyes/Lenguajes/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libro id="L0001" npag="390">
        <claseL tipo_claseL="novela">Novela</claseL>
        <tituloL>Lorem ipsum</tituloL>
        <capituloL npag="100">
            <ctitulo>Lorem ipsum</ctitulo>
            <ccontenido informacionL="...">Lorem ipsum</ccontenido>
        </capituloL>
        <indiceL>Lorem ipsum</indiceL>
        <sinopsisL>Lorem ipsum</sinopsisL>
    </libro>
    <revista id="R" npag="x">
        <claseR tipo_claseR="informatica">Informática</claseR>
        <tituloR>Lorem ipsum</tituloR>
        <nrev>nº2</nrev>
        <indiceR>Lorem ipsum</indiceR>
        <seccionR npag="300">
            <contenidoR informacionR="...">Lorem ipsum</contenidoR>
        </seccionR>
    </revista>
    <periodico id="P0001">
        <claseP tipo_claseP="nacional" fpub="hoy">Nacional</claseP>
        <seccionP tipsec="economica">
            <articuloP autor="nosotros">Lorem ipsum</articuloP>
        </seccionP>
        <indiceP>Lorem ipsum</indiceP>
        <contenidoP informacionP="...">Lorem ipsum</contenidoP>
    </periodico>
</biblioteca>
